# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # this service allows to user to put many files(Cv, Certificate, Diploma, ...) in the database
    user/career/formation/diploma: 'user/career/formation/diploma'

    # this service allows to user to put a profile pic on his profile
    user/profile/avatar: 'user/profile/avatar'

    #this service allows saving docs to provide for each applicant
    user/employability/docs: 'user/employability/docs'

    #this service allows saving the user's CV
    user/career/presentation/cv : 'user/career/presentation/cv'

    #this service allows saving screenshot about error 500
    public/helpCenter/screenshot: 'public/helpCenter/screenshot'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
